[package]
name = "lists"
version = "0.1.0"
authors = ["siegelwang <siegelwang@tencent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
